config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  as :user do
    get '/' => 'devise/sessions#new'
  end

  namespace :api do
    resources :boards do
      resources :lists do
        resources :cards
      end
      resources :cards do
        resources :cardtags
        resources :tasks
      end
      resources :tasks
    end
    resources :cards
    resources :lists
  end

  root to: "devise/sessions#new"
  resources :boards, only: [:index, :show, :new, :create, :destroy] do
    resources :cards, only: [:edit, :update]
    resources :tags, only: [:new, :create]
  end
  resources :cards do
    resources :cardtags
  end
  resources :cardtags
  resources :tags
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :lists
  has_many :tasks
  has_many :cards
  has_many :cardtags
  belongs_to :user

  validates :title, presence: true
  validates_inclusion_of :category, in: %w(calendar kanban custom)

  def self.check_today(board)
    first_list_date = board.lists.first.title.to_datetime
    if (Date.today - 1 > first_list_date)
      board.lists.first.destroy
      new_list_date = (first_list_date + 8).strftime('%a %b %d')
      List.create(title: new_list_date, board_id: board.id)
    end
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :list
  belongs_to :board
  has_many :tasks

  validates :text, presence: true
  validates_inclusion_of :completed, in: [true, false]
  validates :list_id, presence: true
  validates :board_id, presence: true
end

app/models/cardtag.rb
class Cardtag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :card
  belongs_to :board
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :cards
  belongs_to :board
  validates :title, presence: true
  validates :board_id, presence: true

  def self.generate_calendar(date, board_id)
    i = 0
    while i < 8 do
      new_date = date + i
      date_title = new_date.strftime('%a %b %d')
      List.create(title: date_title, board_id: board_id)
      i += 1
    end
  end

  def self.generate_kanban(board_id)
    List.create(title: "To Do", board_id: board_id)
    List.create(title: "In Progress", board_id: board_id)
    List.create(title: "Completed", board_id: board_id)
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :board
  has_many :cardtags
  validates :label, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :card
  belongs_to :board
  validates :text, presence: true
  validates_inclusion_of :completed, in: [true, false]
  validates :card_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :boards
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.send_daily_email
    User.all.each do |user|
      UserMailer.daily_email(user).deliver_now
    end
  end
end

app/controllers/api/cards_controller.rb
class Api::CardsController < ApiController
  def index
    cards = Card.where(board_id: params[:board_id])
    render json: { cards: cards }, status: :ok
  end

  def update
    card = Card.find(params[:id])
    list = List.find(params[:list_id])
    card.update(list_id: params[:list_id])
    cards = Card.where(board_id: params[:board_id])
    render json: { cards: cards }, status: :ok
  end

  def create
    new_card = Card.new(text: params[:text])
    new_card.list = List.find(params[:list_id])
    new_card.board = Board.find(params[:board_id])
    new_card.save
    render json: { card: new_card }, status: :ok
  end

  def destroy
    deleted_card = Card.find(params[:id])
    deleted_card.destroy
    cards = Card.where(board_id: params[:board_id])
    render json: { cards: cards }, status: :ok
  end
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApiController
  def index
    cards = Card.where(board_id: params[:board_id])
    lists = List.where(board_id: params[:board_id])
    tasks = Task.where(board_id: params[:board_id])
    tags = Tag.where(board_id: params[:board_id])
    cardtags = Cardtag.where(board_id: params[:board_id])
    category = Board.find(params[:board_id]).category
    render json: { lists: lists, cards: cards, tasks: tasks, category: category, cardtags: cardtags, tags: tags  }, status: :ok
  end

  def create
    list = List.new(title: params[:text])
    list.board = Board.find(params[:board_id])
    list.save
    render json: { list: list }, status: :ok
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    lists = List.where(board_id: params[:board_id])
    render json: { lists: lists }, status: :ok
  end
end

app/controllers/api/tasks_controller.rb
class Api::TasksController < ApiController
  def create
    task = Task.new(text: params[:name])
    task.card = Card.find(params[:card_id])
    task.board = Board.find(params[:board_id])
    task.save
    render json: { task: task }, status: :ok
  end

  def update
    task = Task.find(params[:id])
    task.update(completed: params[:completed])
    tasks = Task.where(board_id: params[:board_id])
    render json: { tasks: tasks }, status: :ok
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    tasks = Task.where(board_id: params[:board_id])
    render json: { tasks: tasks }, status: :ok
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(users)
    boards_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @boards = Board.where(user: current_user)
  end

  def show
    @board = Board.find(params[:id])
    if @board.category == "calendar"
      Board.check_today(@board)
    end
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    @board.user = current_user
    if @board.save
      if @board.category == "calendar"
        List.generate_calendar(Date.today, @board.id)
      elsif @board.category == "kanban"
        List.generate_kanban(@board.id)
      end
      redirect_to boards_path
    else
      render :new
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_path
  end

  private

  def board_params
    params.require(:board).permit(:title, :category)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    @card.board = Board.find(params[:board_id])
    if @card.update(card_params)
      redirect_to board_path(@card.board)
    else
      flash[:errors] = @card.errors.full_messages.join(', ')
      render :edit
    end
  end

  private

  def card_params
    params.require(:card).permit(:text, :description)
  end
end

app/controllers/cardtags_controller.rb
class CardtagsController < ApplicationController

  def new
    @cardtag = Cardtag.new
    @cardtag.card = Card.find(params[:card_id])
    @board = @cardtag.card.board
    @available_tags = Tag.where(board_id: @board.id)
  end

  def create
    @cardtag = Cardtag.new
    @cardtag.card = Card.find(params[:card_id])
    @cardtag.tag = Tag.find(params[:tag])
    @cardtag.board = @cardtag.card.board
    if @cardtag.save
      redirect_to board_path(@cardtag.board)
    else
      render :new
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
    @tag = Tag.new
    @tag.board = Board.find(params[:board_id])
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.board = Board.find(params[:board_id])
    if @tag.save
      redirect_to board_path(@tag.board)
    else
      render :new
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:label, :color, :board_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <%= f.text_field :title, placeholder: "Title" %>
  <div>
    <%= f.radio_button :category, "calendar" %>
    <%= f.label :category, "Calendar" %>
    <%= f.radio_button :category, "kanban"  %>
    <%= f.label :category, "Kanban"  %>
    <%= f.radio_button :category, "custom"  %>
    <%= f.label :category, "Custom"  %>
  </div>
  <%= f.submit%>
<% end %>

app/views/boards/index.html.erb
<div class="board-list-header">
  <span class="title">My Boards</span>
  <span class="new-board">
    <i class="fa fa-plus-square" aria-hidden="true">
    <%= link_to "New Board", new_board_path%>
    </i>
  </span>
</div>
<div >
  <% @boards.each do |board| %>
    <div class="small-4 columns end">
      <div class="board">
        <span class="board-icon-div">
          <% if board.category == "calendar" %>
            <i class="board-icon fa fa-calendar"></i>
          <% elsif board.category == "kanban" %>
            <i class="board-icon fa fa-tasks"></i>
          <% elsif board.category == "custom" %>
            <i class="board-icon fa fa-user"></i>
          <% end %>
        </span>
        <span class="board-title"><%= link_to board.title, board_path(board)%></span>
        <span class="board-trash-div">
          <%= link_to "", board, method: :delete, data: { confirm: 'Are you sure?' }, class: "board-trash fa fa-trash-o" %>
        </span>
      </div>
    </div>
  <% end %>
</div>

app/views/boards/new.html.erb
<div class="row">
  <div class="blank small-4 column">blank</div>
  <div class="small-4 column">
    <h3>Create New Board</h3>
    <%= render 'form' %>
  </div>
  <div class="blank small-4 column">blank</div>
</div>

app/views/boards/show.html.erb
<span class="title"><%= @board.title %></span><br/>
<span class="new-tag-link">
  <i class="fa fa-plus"></i>
  <%= link_to "Create New Tag", new_board_tag_path(@board), class: "secondary-button" %>
</span>
<div id="board">
</div>

app/views/cards/edit.html.erb
<div class="row">
  <div class="blank small-4 column">blank</div>
  <div class="small-4 column">
    <h3>Edit Card</h3>
    <%= form_for([@card.board, @card]) do |f| %>
      <%= f.text_field :text, placeholder: "Text" %>
      <%= f.text_field :description, placeholder: "Description" %>

      <div class="log-in"><%= f.submit%></div>
    <% end %>
    <div class="shared-links">
      <%= link_to "Add Tag to Card", new_card_cardtag_path(card_id: @card.id), class: "secondary-button" %><br />
    </div>
  </div>
  <div class="blank small-4 column">blank</div>
</div>

app/views/cardtags/new.html.erb
<div class="row">
  <div class="blank small-4 column">blank</div>
  <div class="small-4 column">
    <h3>Add Tag to "<%= @cardtag.card.text %>"</h3>
    <%= form_for([@cardtag.card, @cardtag]) do |f| %>
      <% @available_tags.each do |tag| %>
        <%= check_box_tag :tag, tag.id %>
        <%= f.label :tag, tag.label %>
      <% end %>
      <%= f.submit%>
    <% end %>
  </div>
  <div class="blank small-4 column">blank</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuToDo</title>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">  <link rel="stylesheet" href="https://cdn.jsdelivr.net/foundation/6.2.1/foundation.min.css">
  <script src="https://cdn.jsdelivr.net/foundation/6.2.1/foundation.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>
<body>

<% if request.env['PATH_INFO'] == "/" || request.env['PATH_INFO'] == "/users/sign_in" || request.env['PATH_INFO'] == "/users/sign_up" %>
  <% flash.each do |name, msg| %>
    <% if name == "success" || name == "notice" %>
      <%= content_tag :div, msg, class: "flash callout success" %>
    <% else %>
      <%= content_tag :div, msg, class: "flash callout alert" %>
    <% end %>
  <% end %>
  <div class="landing-page">
    <%= yield %>
  </div>
<% else %>
  <div class="header">
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="menu">
          <li class="logo"><%= link_to "AuToDo", boards_path %></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li><%= link_to "Dashboard", boards_path %></li>
          <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li><%= link_to "Log In", root_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>


  <div id="body">
    <% flash.each do |name, msg| %>
      <% if name == "success" || name == "notice" %>
        <%= content_tag :div, msg, class: "flash callout success" %>
      <% else %>
        <%= content_tag :div, msg, class: "flash callout alert" %>
      <% end %>
    <% end %>
    <%= yield %>
  </div>
<% end %>

</body>
</html>

app/views/tags/new.html.erb
<div class="row">
  <div class="blank small-4 column">blank</div>
  <div class="small-4 column">
    <h3>Create Tag</h3>
    <%= form_for([@tag.board, @tag]) do |f| %>
      <%= f.text_field :label, placeholder: "Label" %>
      <div><%= f.submit%></div>
    <% end %>
  </div>
  <div class="blank small-4 column">blank</div>
</div>